name: Deploy Docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build-dpdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ubuntu-version: 22.04
            dpdk-version: 22.07
            tag: 22.07
          - ubuntu-version: 22.04
            dpdk-version: 21.11.2
            tag: 21.11
          - ubuntu-version: 22.04
            dpdk-version: 20.11.6
            tag: 20.11
          - ubuntu-version: 22.04
            dpdk-version: 19.11.13
            tag: 19.11
          - ubuntu-version: 22.04
            dpdk-version: 18.11.11
            tag: 18.11
          - ubuntu-version: 22.04
            dpdk-version: 17.11.10
            tag: 17.11

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BASE_IMG=ubuntu:${{ matrix.ubuntu-version }}
            DPDK_VERSION=${{ matrix.dpdk-version }}
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            duskmoon/dpdk:${{ matrix.tag }}
            ghcr.io/duskmoon314/dpdk:${{ matrix.tag }}
          cache-from: type=registry,ref=ghcr.io/duskmoon314/dpdk:${{ matrix.tag }}
          cache-to: type=inline